spring:
  main:
    banner-mode: off

  #  h2:
  #    console.enabled: true

  sql:
    init:
      mode: always

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    drop-first: true

logging:
  level:
    root: INFO
    test: DEBUG

  file:
    name: appBank.log

  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}
    %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

